Repository tieme-ndo/frontend, pull requests merged in 2019-09, with the labels that each got.

#47 Display Image in Farmer Page
  src/components/pages/DisplayFarmer/LeftDisplay.js
  yarn.lock
Labels: enhancement

#63 Fixing Update Farmer Submit on missing inputs
  src/components/pages/UpdateFarmer/UpdateFarmer.js
  src/utils/handlers/farmerHandlers.js
Labels: bug

#75 Refactoring Error Return
  src/components/App/App.js
  src/utils/handlers/authenticationHandlers.js
  src/utils/handlers/farmerHandlers.js
  src/utils/handlers/userHandlers.js
Labels: Refactoring

#69 Fix: Farmer Form Image Inputs
  src/components/common/Input/ImageInputContainer.js
  src/components/common/Input/Input.js
  src/components/common/Input/addFarmerData.js
  src/components/pages/AddFarmer/AddFarmer.js
  src/components/pages/UpdateFarmer/UpdateFarmer.js
  src/components/pages/UpdateFarmer/UpdateFarmer.spec.js
Labels: bug

#78 Refactoring Restricted Routes HOC
  src/components/App/App.js
  src/components/hoc/RestrictedRoute.js
  src/components/hoc/RestrictedRoute.spec.js
  src/components/hoc/withRestrictedAccess.js
  src/components/pages/Dashboard/Dashboard.js
  src/components/pages/DisplayFarmer/DisplayFarmer.js
  src/components/pages/EditCollection/EditCollection.js
  src/components/pages/PasswordReset/PasswordReset.js
  src/components/pages/UpdateFarmer/UpdateFarmer.js
  src/utils/handlers/authenticationHandlers.js
Labels: Refactoring

#82 FIXED: Refactoring Request Headers
  src/components/pages/AddFarmer/AddFarmer.js
  src/components/pages/AddStaff/AddStaff.js
  src/components/pages/PasswordReset/PasswordReset.js
  src/components/pages/UpdateFarmer/UpdateFarmer.js
  src/utils/axiosWithHeaders.js
  src/utils/generalVariables.js
  src/utils/handlers/authenticationHandlers.js
  src/utils/handlers/changeRequestHandler.js
  src/utils/handlers/farmerHandlers.js
  src/utils/handlers/userHandlers.js
  src/utils/requestHeaders.js
Labels: Refactoring

#86 Fix change request by Id Bug (is run two times)
  src/components/pages/EditCollection/EditCollection.js
  src/utils/handlers/changeRequestHandler.js
Labels: Ready for QA

#92 Fix bell and menu
  src/components/common/PageHeader/PageHeader.js
  src/components/common/Sidebar/Sidebar.js
Labels: Ready to be merged

#93 Statistics error handling
  src/components/App/App.js
  src/utils/handlers/farmerHandlers.js
Labels: Ready for QA

#88 Check pw before changing pw
  src/components/pages/PasswordReset/PasswordReset.js
  src/components/pages/PasswordReset/PasswordReset.spec.js
  src/components/pages/PasswordReset/PasswordResetForm.js
  src/components/pages/PasswordReset/resetPasswordValidation.js
  src/utils/handlers/userHandlers.js
Labels: Ready for review

#83 created confirm passsword field
  src/components/pages/AddStaff/AddStaff.js
  src/components/pages/AddStaff/AddStaff.spec.js
  src/components/pages/AddStaff/AddStaffForm.js
  src/components/pages/AddStaff/AddStaffValidation.js
Labels: Ready to be merged

#94 Remove warning logs from frontend tests
  src/components/pages/EditCollection/EditCollection.js
  src/utils/handlers/changeRequestHandler.js
Labels: Ready for review

#91 Style Fix: Header & Sidebar Scroll Issues + Minor Style Tweaks
  src/components/App/App.js
  src/components/common/PageHeader/PageHeader.js
  src/components/common/Sidebar/Sidebar.js
  src/components/pages/AddFarmer/AddFarmer.js
  src/components/pages/UpdateFarmer/UpdateFarmer.js
  src/components/partials/FarmersStatistic.js
Labels: Ready for review

#98 Check for non-alphanumeric characters in username
  src/components/pages/AddStaff/AddStaff.js
Labels: Changes requested. Pls fix

#99 bug(axios): handle network error globally
  src/components/App/App.js
  src/components/hoc/axiosErrorHandler/AxiosErrorInterceptor.js
  src/components/pages/AddFarmer/AddFarmer.js
  src/components/pages/AddStaff/AddStaff.js
  src/components/pages/EditCollection/EditCollection.js
  src/components/pages/Login/Login.js
  src/components/pages/PasswordReset/PasswordReset.js
  src/components/pages/PasswordReset/PasswordResetForm.js
  src/components/pages/UpdateFarmer/UpdateFarmer.js
  src/utils/handlers/userHandlers.js
Labels: Ready for QA
